// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/press-bar/PressBar.tsx": () => import("../components/mockups/press-bar/PressBar.tsx"),
  "./components/mockups/pull-quotes/PullQuotes.tsx": () => import("../components/mockups/pull-quotes/PullQuotes.tsx"),
  "./components/mockups/testimonials/Testimonials.tsx": () => import("../components/mockups/testimonials/Testimonials.tsx")
};
